### ISSUE TITLE
Data structures in GGXF headers 

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#10]
To create meaningful examples of deformation model GGXF files (in a text format) requires encoding a nested data structured of information in the headers, in particular time functions.   The text exampls and GGXF specification is based on a list of key-value pairs.  How should a time function, or other structured data, be encoded in this format?

At a high level the structure of the deformation model could look like the following pseudo YAML:

```
   deformation_model
      - component
          spatial_model:
              - grid
              - grid
          time_function:
              - function_type: piecewise
                data_points: 
                   - epoch: 2015-05-02
                     multiplier: 0.8
                   - epoch: 2015-06-13
                     multiplier: 1.5
              - function_type: exponential
                reference_epoch: 2010-03-04
                decay_rate: 0.8
                amplitude: 1.3
                ....
     - component
       ...
```

This structure is a list of components, each of which has attributes including spatial_model and time_function.  The spatial model is primarily an array of grids.  The time function comprises one or more base functions which are added to complete form the total time function.  One options for time functions is piecewise linear, which is defined by a list of time/multiplier values.  This may be simplified slightly as we develop the deformation model specification but it is likely to be something like this.

Some of this structure is inherent in the GGXF specification.  The GGXF holds multiple grids which are partitioned into groups.  For a deformation model each group is a component, and the spatial model is defined by the grids in that group.   However the time function must be encoded into the group header.  

The format for describing headers is a list of key-value pairs.  To use an example from the draft GGXF specification:

```
ggxfVersion			1.0
filename			27to83.gxb
content			geographic2dOffsets
version			National Transformation v2_0
licence			https://open.canada.ca/en/open-government-licence-canada
contentBox
  southBoundLatitude 		40.0
  westBoundLongitude		-142.0
  northBoundLatitude 		60.0
  eastBoundLongitude 		-44.0
contentApplicabilityBox
  southBoundLatitude 		40.0
  westBoundLongitude		-141.0
  northBoundLatitude 		60.0
  eastBoundLongitude 		-88.0
extentApplicability 	Canada south of 60°N

interpolationCrsWkt 	GEOGCRS["NAD27",
					DATUM["North American Datum 1927",
					ELLIPSOID["Clarke 1866",6378206.4,294.9786982,
					  LENGTHUNIT["metre",1]]],
					CS[ellipsoidal,2],
					AXIS["Geodetic latitude (Lat)",north],
					AXIS["Geodetic longitude (Lon)",east],
					ANGLEUNIT["degree",0.0174532925199433]]
...
parameterCount 		4
parameter 			latitudeOffset arc-second angle 0.0000048481368111
parameter 			longitudeOffset arc-second angle 0.0000048481368111
parameter 			latitudeOffsetUncertainty metre length 1.0
parameter 			longitudeOffsetUncertainty metre length 1.0
```

Three points relevant to encoding time functions show here:
* representation of contentBox and contentApplicability box already appears to be a nested data structure, rather than a simple key/value pair list
* interpolationCrsWkt uses a text encoding of a data  structure as a value
* a list has been encoded with a parameter count followed by repeated instances of a parameter key-pair value

In order to understand how create meaningful examples for the deformation model we need to be clear what the structure of the headers. 

I believe there are two basic options.  

1. Define a structured format as part of the GGXF specification, which appears to be what we are doing in this example.  For example the parameterCount header does not just provide a parameter count, it defines a list data structure and instructs the reader to expect to read 4 parameter keys.  This also means that the list of key-pair values is an ordered list, at least for some elements such as parameter.  There are some rules about the structure of headers that are currently not explicit in the current GGXF specification.

2. Use an existing schema and data structure encoding (eg JSON and JSON schema, XML, etc).  The GGXF still has to specify a schema, but it doesn't have to specify (or imply) a schema language.

I think at the moment we are creating text examples to demonstrate that GGXF can encode the data types of interest. But without clarity on how data structures should be encoded I'm not sure how we can do that.  

Looking briefly at the NetCDF website (as a potential candidate implementation) I do not see any discussion of structured data.  So we may need to decide how to encode data structures in GGXF in any case.  In that case I think we should use an existing structured text format.  That way implementers do not have to write their own parser of complex text attributes - they can use standard parsers and only need to be concerned with using the data structure.

**Comment by kevinmkelly** [comment]
Thanks for this, Chris. It's quite needful to begin to address the details of encoding and a schema of header information. I offer the following suggestion and hope it does not reveal my ignorance. 

I know little about encoding languages. But, would it be reasonable to develop a schema using the verbose XML language or JSON directly? I'm thinking that there must be tools to use to guide the process and to test for logic/structural inconsistencies. I suggest this only on the condition that tools also exist to translate/convert XML/JASON into other popular, well-defined encoding languages (I don't know if they do). Does this make sense?

**Comment by ccrook** [comment]
@KRyden @kevinmkelly @RogerLott I thought I had put this in an email a week or so ago but find no record of it, so I suspect I mislaid it.  However this is possibly a clearer exposition.  Hopefully :-)  Obviously some of this structure may be dictated from the chosen carrier (eg GeoTIFF includes an embedded XML structure, not sure about NetCDF but could use JSON, XML, or some other structure encoded into a text parameter (documentation seemed focussed on a couple of language implementations rather than data structure).  The data types description however include a description of compound types (NetCDF-4, implementing HDF5).  See https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/md_types.html#types_compound_types

**Comment by ccrook** [comment]
@kevinmkelly The structure could certainly be described in XML - as you doubtless know there is an XML schema for describing XML schemas!  There is also a project for defining a JSON based schema, though I believe it is much less well established.  I'm not familiar with tools, but I guess there will be lots, particularly for XML schema.   

In terms of the current work creating example files in text format I am just trying to get clarity about how encode the structured data.  I'm not sure how far we want to go with the text format - possibly it will be sufficiently structured that it can become a source format for creating GGXF files?

**Comment by ccrook** [comment]
21 June 2021 meeting:  Agreed that we will try using YAML format to represent header structure.
CC to convert deformation model example headers in GGXF file to YAML.

**Comment by ccrook** [comment]
23-5 meeting: 

Raised the question of should the data be more structured.  Question raised for applicabilityExtent eg

```
applicabilityExtent:
    description: Text description of extent for human consumption
    boundingBox:
      southBoundLatitude: -58.0
      westBoundLongitude: 158.0
      northBoundLatitude: -25.0
     eastBoundLongitude: 194.0  
   polygon:  # Optional polygon definition - format to descide
```
Also for parameters:

```
    parameters:
      - name: displacementEast
        unit: metre
        conversionToMetres: 1.0
```
