### ISSUE TITLE
Additional structure in GGXF headers

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#13]
Should the GGXF header data be more structured?

Several of the fields in the GGXF have implicit structure.  Two examples:

Parameters are currently written as for example:

```
  parameters:
  - displacementEast metre length 1.0
  - displacementNorth metre length 1.0
```

This could be structured tas 

```
  parameters:
  - name: displacementEast 
    unit: metre 
    dimension: length 
    conversionToSI: 1.0
  - name: displacementNorth
    unit: metre 
    dimension: length 
    conversionToSI: 1.0
```

Similarly the extent is currently describe by two parameters as:

```
contentApplicabilityExtent:
  southBoundLatitude: -58.0
  westBoundLongitude: 158.0
  northBoundLatitude: -25.0
  eastBoundLongitude: 194.0
contentApplicabilityExtentDescription: New Zealand EEZ
```

These could be considered as elements of the same attribute, such as:

```
applicabilityExtent:
  description: New Zealand EEZ
  boundingBox: 
    southBoundLatitude: -58.0
    westBoundLongitude: 158.0
    northBoundLatitude: -25.0
    eastBoundLongitude: 194.0
 polygon: POLYGON((....))
```
(here adding an optional polygon definition)

There are other candidates for structured data, such as addresses, links to references.  For some there may be established standards for such structures which it would make sense to adopt.  

This issue is to discuss whether we want to add such extra structure, and if so to track discussion on the structures we might want to add.
