### ISSUE TITLE
NetCDF structure optimisation

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#22]
The current proposed structure of the GGXF NetCDF file for a nested grid is along the lines of

``` yaml
root:
  groups:
   - name: groupid1
     grids:
       - name: gridid1
         extents: affine and row counts
         data: [ ... ]
         grids:
           - name: gridid2
             extents: affine and row counts
             data: [ ... ]
           - name: gridid3
             extents: affine and row counts
             data: [ ... ]
```

Here extents represents the information that defines the extent of a grid, ie affineCoeffs, iNodeMaximum, jNodeMaximum.  Also note that in NetCDF grids and groups are both NetCDF Group objects.  It is only the GGXF structure that identifies some as representing GGXF groups, and others as GGXF grids.

This structure creates a similar issue to that described for YAML in #12 which is that the extent information of the nested grids is scattered through the GGXF file. 

For a nested grid structure most or all of the extent information will need to be read to decide which grid to use at a location.  However often only the data from one grid will be needed by for a job.  For example in the Canadian NTv2 grid a conversion of data in Banff requires only the tiny nested grid for that area.  

While scanning the entire file to extract the extent information is fast as NetCDF uses direct access, it still requires accessing a large portion of the file.  

It may be better optimised to alternative grid format move the grid data to a separate group in the GGXF file, so that all the required extent information is close together at the beginning of the GGXF file, and the data is in one or more data groups at the end of the file. 
 This is analogous to the cloud optimised GeoTIFF format, which brings the TIFF index information to the front of the file.  The structure would therefore be more like:

``` yaml
root:
  groups:
   - name: groupid
     grids:
       - name: gridid
         extents: affine and row counts
         grids:
           - name: gridid
             extents: affine and row counts
           - name: gridid
             extents: affine and row counts
  ...
  - name: gridData
    gridid1: [....]
    gridid2: [....]
```

The gridData group would have variables for each grid (or possibly groups containing variables for each grid).  The variable would include NetCDF dimensions defining the number of rows, columns, and parameters  in the grid.

This is a further break from the conventional NetCDF usage, but since we are already (under the current proposal) using the format, not the conventions, of NetCDF that may not be a good reason to not do this.
