### ISSUE TITLE
Variables more similar to NetCDF common usage

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#28]
# Current state
The current prototype produces a file with the following structure (example derived from NTv2):

```
group: National\ Transformation\ v2_0 {
  dimensions:
    parameter = 4 ;

  // group attributes:
    :parameters.count = 4LL ;
    :parameters.0.parameterName = "latitudeOffset" ;
    :parameters.0.angleUnit = "arc-second" ;
    :parameters.0.unitSiRatio = 4.84813681109536e-06 ;
    :parameters.1.parameterName = "longitudeOffset" ;
    :parameters.1.angleUnit = "arc-second" ;
    :parameters.1.unitSiRatio = 4.84813681109536e-06 ;
    :parameters.2.parameterName = "latitudeOffsetUncertainty" ;
    :parameters.2.lengthUnit = "metre" ;
    :parameters.2.unitSiRatio = 1. ;
    :parameters.3.parameterName = "longitudeOffsetUncertainty" ;
    :parameters.3.lengthUnit = "metre" ;
    :parameters.3.unitSiRatio = 1. ;
    :uncertaintyMeasure = "2CEE" ;
    :interpolationMethod = "bilinear" ;

  group: CAeast {
    dimensions:
      gridi = 529 ;
      gridj = 241 ;
    variables:
      float data(gridj, gridi, parameter) ;

    // group attributes:
      :iNodeMaximum = 528LL ;
      :jNodeMaximum = 240LL ;
      :affineCoeffs = 60., 0., -0.0833333333333333, -88., 0.0833333333333333, 0. ;
```

# Issue
Minor note: `jNodeMaximum` and `jNodeMaximum` are redundant with `gridi` and `gridj` dimensions. I think they could be omitted. Less redundancy is less risk of inconsistency.

My main concern is that above structure does not follow the usual netCDF practice. Even if we do not adopt fully the CF-conventions, I propose to nevertheless use them when they make sense. It would reduce users and developers effort by providing files that look more familiar to them. It also increases the chances that readers not aware of GGXF format can nevertheless understand those files at least partially. It would also enable the use of other CF-conventions such a packing mentioned in #23. Similar arguments were also expressed in https://github.com/opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format/issues/17#issuecomment-938541362.

# Proposal
I propose to remove all `parameters*` attributes and replace them by the use of CF-Convention. For this issue I will take the following definitions (Roger or Chris, please correct me if I mix up those definitions):

* **Interpolation CRS:** the CRS in which are expressed the grid coordinates (after affine transform).
* **Target CRS:** the CRS of coordinates on which to apply displacement vectors.
* _The interpolation CRS and the target CRS do not necessarily have the same number of dimensions._ We could have 3D displacement vectors in a 2D grid, or conversely. They do not need to use the same units of measurement neither.

For each group, the netCDF dimensions (not to be confused with CRS dimensions) of geodetic variables are as below (note: this is the same as current prototype except for the last dimension - `parameter` - which is replaced by `axis`):

* One netCDF dimension for each *Interpolation CRS* dimension. The number of those netCDF dimensions is the number of interpolation CRS dimensions, which is also the number of dimensions of the GGXF grid (not necessarily in same order - the affine transform allows axis order change). The length of each netCDF dimension is the number of cells of the grid along that dimension.
* A single dimension for all *Target CRS* axis. The length of this dimension is the number of target CRS dimensions.

In above NTv2 example the interpolation CRS is two-dimensional. So geodetic coordinates are (x,y), which is mapped by the affine inverse transform to grid coordinates (i,j). So we have two netCDF dimensions: `gridi` and `gridj` (I will use `i` and `j` bellow for brevity). If the interpolation CRS was three-dimensional, we would have three netCDF dimensions: `i`, `j` and `k`.

Then we add *exactly one* netCDF dimension which stands for _target CRS_ dimensions. I will name that netCDF dimension "axis", but a longer description would be _"index of target CRS axis"_. The length of this dimension is always the number of target CRS dimensions. So if the target CRS is two-dimensional, then we have exactly one `axis` dimension of length 2. If the target CRS is three-dimensional, then we have exactly one `axis` dimension of length 3.

Finally, we create one netCDF variable for each parameter _with all target CRS axes grouped together in the same variable_. In the NTv2 example we have:

* One `offset` variable which contains the "latitudeOffset" and "longitudeOffset" parameters.
* One `uncertainty` variable which contains the "latitudeOffsetUncertainty" and "longitudeOffsetUncertainty" parameters.

Complete example rewritten with this proposal (an open question is whether target CRS axis should be a global dimension or specified on a group-by-group basis. Following proposal takes the later approach):

```
group: National\ Transformation\ v2_0 {

  // group attributes:
    :uncertaintyMeasure = "2CEE" ;
    :interpolationMethod = "bilinear" ;

  group: CAeast {
    dimensions:
      i = 529 ;
      j = 241 ;
      axis = 2 ;
    variables:
      float displacement(j, i, axis) ;
      float uncertainty(j, i, axis) ;

    // group attributes:
      :affineCoeffs = 60., 0., -0.0833333333333333, -88., 0.0833333333333333, 0. ;
```

If the target CRS uses (latitude, longitude) axis order, then:

* `displacement(j, i, 0)` means `latitudeOffset(j, i)` (indices are zero-based).
* `displacement(j, i, 1)` means `longitudeOffset(j, i)`.
* `uncertainty(j, i, 0)` means `latitudeOffsetUncertainty(j, i)`.
* `uncertainty(j, i, 1)` means `longitudeOffsetUncertainty(j, i)`.

If the displacement vectors were three-dimensional, then:

*  `axis` would be of length 3 instead of 2.
* `displacement(j, i, 2)` would mean `heightOffset(j, i)`.

I think this approach would also be easier for implementer and less bug-prone, because it establishes a very clear and unambiguous relationship between indices and CRS axes. I'm not sure how this proposal would apply to other use cases than NTv2 datum shift, but my hope is that the core idea (which is to associate a netCDF dimension to the axes of some CRS) would still apply.

# Bonus
CF-conventions can be applied when useful (we do not need to adopt all of them, but at least the useful parts). Below is an example using packed data (see #23). Note that it would not be possible with all parameters in a single `data` variable, because units, scale factor, _etc._ are not the same for all parameters.

```
    variables:
      short displacement(j, i, axis) ;
        translation::scale_factor = 0.0001;
        translation::add_offset = -0.005;
        translation::units = "arc-second"
      short uncertainty(j, i, axis) ;
        uncertainty::scale_factor = 0.001;
        uncertainty::add_offset = -0.05;
        uncertainty::units = "metre"
```

**Comment by ccrook** [comment]
> Minor note: jNodeMaximum and jNodeMaximum are redundant with gridi and gridj dimensions. I think they could be omitted. Less redundancy is less risk of inconsistency.

I agree totally on this.  I had suggested changing to use the dimensions (offset by 1 from i/jNodeMaximum), but Roger was not keen.  OTOH it may be sufficient for NetCDF to accept that they are logically defined by the dimensions even if they are not explicitly defined as attributes.

**Comment by ccrook** [comment]
> Below is an example using packed data (see #23). Note that it would not be possible with all parameters in a single data variable, because units, scale factor, etc. are not the same for all parameters.

I also think packing would be worth looking at.  I think that is independent of the use of units and distribution of parameters amongst variables, though obviously it will be most effective where the range of values of each parameter in the variable is similar. Uncertainty (and certainly significant uncertainty) will be likely to lie in the same range as the parameter whose uncertainty it reflects, unless there is a significant offset involved.  

I've added the following comment to the README for the moment:

> Consider the use of NetCDF packing for efficient storage of data (eg automatic testing of parameter range and implementing packing were suitable)

**Comment by ccrook** [comment]
... which gets to the main question - should we split the data, or provide an option for splitting the data, into more than one variable in the GGXF group.  In terms of NetCDF conventions I suspect we are not compliant unless we make it one variable (grid) per parameter.  

We are not following the conventions in any case (eg we are using an affine transformation for spatial definition rather than latitude and longitude value arrays).  I think our approach is good in this regard.  So in my mind this is not a question of our alignment or otherwise with the conventions, but whether there is an advantage to us in providing an option for splitting the grid into two or more NetCDF variables.

I think the arguments are:

Pro: efficiency, particularly in separating uncertainty, as many software will handle the deterministic parameters but not use the uncertainty data.  In this case placing the data in separate variables will improve the efficiency as the required data would be more closely located in the NetCDF file and so more efficiently accessed.

Cons: It adds to the complexity of implementation, eg for each content type (possilby each GGXF grid) the assignment of variable to parameters must be defined.   To provide a benefit GGXF libraries must support providing a subset of parameters.

Note: The benefits could be achieved (possibly even more effectively) by splitting the uncertainty into a separate GGXF group (ie supporting this explicitly at the GGXF level rather than implicitly at the NetCDF variable.   This would provide an additional potential benefit that the uncertainty could use much simpler grids as it is likely to be much smoother, and has much lower accuracy requirements.  This could allow for a further reduction in the total size of a GGXF file.

**Comment by ccrook** [comment]
Thinking about potential implementation I am wondering if the following would suffice:

* add an optional "precision" attribute to either the the GGXF group header or parameter definition that can be used to implement packing.  Also a "default precision" option either in the GGXF header or as a file creation option for netCDF file creation.  (Mainly want both for deformation, where eg velocity grid would have different precision to coseismic deformation grid). For YAML the attribute wouldn't affect the grid data but it would be retained and used when data is persisted to NetCDF

* if we follow Martin's suggestion of creating multiple variables in a GGXF grid we could add a "parameter group" attribute to the group header parameter group.  Parameters with the same group would be put in the same NetCDF variable.  For YAML there probably isn't any benefit in splitting the data into multiple grids so again it would be implemented in the NetCDF level.  

* If we use GGXF groups to split eg uncertainty from displacements then there would be no change to the file formats.  The code for calculating values also already handles this for deformation (where for example one group might define horizontal velocity and another 3d coseismic displacements).  So this would be a far smaller change codewise.  

Also both options for splitting the data could be supported (ie multiple variables in a GGXF grid header and splitting parameters across groups)

So the YAML group header could look something like:

``` yaml
    parameters:
      - parameterName: latitudeOffset
        parameterGroup: offset
        angleUnit: arc-second
        unitSiRatio: 4.84813681109536E-06
        precision: 0.00001
      - parameterName: longitudeOffset
        parameterGroup: offset
        angleUnit: arc-second
        unitSiRatio: 4.84813681109536E-06
        precision: 0.00001
      - parameterName: latitudeOffsetUncertainty
        parameterGroup: uncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        precision: 0.001
      - parameterName: longitudeOffsetUncertainty
        parameterGroup: uncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        precision: 0.001
```

The parameterGroup attribute would be used to define the NetCDF variable name holding the parameter and would have default value "data" reflecting the current name and the YAML variable name.  The YAML file would still have the a single grid with the parameters in the specified order.

Here precision would optionally be used to support packing of data in NetCDF.  It would take a default value from the NetCDF file creation options (ie command line parameter) or if none is specified then no NetCDF packing would be attempted.

**Comment by desruisseaux** [comment]
One major goal of this proposal is to establish an unambiguous relationship between CRS axes and parameters. If a parameter name is `latitudeOffset`, is it for the first or the second axis of the CRS? In current state it requires either fragile heuristic such as parsing the "latitude" part of the name and try to match that to the name of a CRS axis, or assuming that parameters are listed in the same order than axes. But it still difficult: is `latitudeOffsetUncertainty` the beginning of a new set of parameters to associate to axes, or some standalone parameter?

I think that we need to establish a formal relationship between parameters such as "latitude offset" and CRS axes. The most straightforward and unambiguous mechanism I could imagine in a netCDF file would be to assign a netCDF dimension to axis index. So every parameters for which there is one value per CRS axis should have an `axis` dimension. In a two-dimensional grid, we would have a 3-dimensional netCDF variable such as `float offset(j, i, axis)`. In a three-dimensional grid, we would have a 4-dimensional netCDF variable, _etc._ The `axis` dimension would always be last in the list of netCDF dimensions.

Rewriting above YAML with this idea in mind, we could have something like below. The `axisName` are for informative purpose since they duplicate ISO 19111 axis name (maybe we should omit them). So the first parameter is `offset`, the first axis block inside `offset` describes the `offset(j,i,0)` values, the second axis block inside `offset` describes the `offset(j,i,1)` values, _etc._ if there is more CRS dimensions.

```yaml
parameters:
    - parameterName: offset
        - axisName: latitude
          angleUnit: arc-second
          unitSiRatio: 4.84813681109536E-06
          precision: 0.00001
        - axisName: longitude
          angleUnit: arc-second
          unitSiRatio: 4.84813681109536E-06
          precision: 0.00001
    - parameterName: offsetUncertainty
        - axisName: latitude
          lengthUnit: metre
          unitSiRatio: 1.0
          precision: 0.001
        - axisName: longitude
          lengthUnit: metre
          unitSiRatio: 1.0
          precision: 0.001
```

**Comment by ccrook** [comment]
That certainly could work.  This would conflict with #30 that I created yesterday, at least if we consider the "Note 3" which suggests that the parameter definitions could be moved up to file header level, with the group header just saying which of the parameters were used (to enforce consistent definition in files with multiple groups - so once again mainly deformation).  However that hasn't received any comment as yet.  So ignoring the extension of the original idea in #30 this would be:

```yaml
parameters:
    - parameterName: offset
      axes:
        - axisName: latitude
          angleUnit: arc-second
          unitSiRatio: 4.84813681109536E-06
          precision: 0.00001
        - axisName: longitude
          angleUnit: arc-second
          unitSiRatio: 4.84813681109536E-06
          precision: 0.00001
    - parameterName: offsetUncertainty
      axes:
        - axisName: latitude
          lengthUnit: metre
          unitSiRatio: 1.0
          precision: 0.001
          uncertaintyMeasure: 2EP
        - axisName: longitude
          lengthUnit: metre
          unitSiRatio: 1.0
          precision: 0.001
          uncertaintyMeasure: 2EP
```

I added axes to make the structure correct.  In this case uncertaintyMeasure could be raised to the level of the parameter, rather than axes. But that wouldn't always work (eg latitude, longitude, height axes).

This does presume that the GGXF is only used for corrections to coordinate axes directly.  At the moment all our example are that.  But Kevin was considering that there may be data sets which were structured differently, in which the gridded data were coefficients for formulae to calculate corrections.   This could perhaps be handled by using some more generic term than "axisName".
