### ISSUE TITLE
Where should parameter definitions be placed in the GGXF structure?

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#30]
The GGXF specification currently proposes an attribute "uncertaintyMeasure" which is used to describe the statistical characteristics of this parameter, eg 1SE, 2CEP.  Because some types include both horizontal and vertical parameters with different uncertainty measures it has been proposed that this would have to be structured, something like 

``` yaml
uncertaintyMeasure:
   horizontal: 2CEP
   vertical: 2SE
```

This adds some complexity to software which needs to have table relating parameters to uncertainty measures.  For example a deformation model may have parameters displacementEastUncertainty, displacementNorthUncertainty, and displacementUpUncertainty.  The software needs to identify which uncertaintyMeasure applies to which parameter.  This is intuitive to a human reader but must be defined programmatically for software, and defined for each type of GGXF file.

In the 31 Jan 2022 GGXF meeting it was proposed that instead the uncertainty measure is included in the parameter definition in the GGXF group.  This would be a conditional attribute of a parameter that would apply if the parameter defines uncertainty.  For example:

``` yaml
    parameters:
      - parameterName: latitudeOffset
        angleUnit: arc-second
        unitSiRatio: 4.84813681109536E-06
      - parameterName: longitudeOffset
        angleUnit: arc-second
        unitSiRatio: 4.84813681109536E-06
      - parameterName: latitudeOffsetUncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        uncertaintyMeasure: 2CEP
      - parameterName: longitudeOffsetUncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        uncertaintyMeasure: 2CEP
```

This removes any ambiguity in associating the uncertaintyMeasure(s) with the corresponding parameters.

**Note 1**: Perhaps GGXF specification should also add a requirement that within a single GGXF file the uncertainty measure for a specific parameter is the same for every group.  In fact possibly this should apply to all parameter attributes - ie if the unit of displacementEast is metre in one group, then it must be metre in all groups which have that parameter.

**Note 2**: It has been proposed that the GGXF group/file header also include an optional defaultUncertainty attribute that would be used to record the uncertainty of a parameter if it is not explicitly defined in the grid data.  In order to be consistent with this approach I suggest this would be formatted as:

``` yaml
    uncertaintyDefault:
      - parameterName: latitudeOffsetUncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        uncertaintyMeasure: 2CEP
        value: 0.05
      - parameterName: longitudeOffsetUncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        uncertaintyMeasure: 2CEP
        value: 0.05
```

**Note 3**

As an even larger change, the list of parameters in a GGXF file could be included in the **file** header as:

``` yaml
    parameters:
      - parameterName: latitudeOffset
        angleUnit: arc-second
        unitSiRatio: 4.84813681109536E-06
      - parameterName: longitudeOffset
        angleUnit: arc-second
        unitSiRatio: 4.84813681109536E-06
      - parameterName: latitudeOffsetUncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        uncertaintyMeasure: 2CEP
        defaultValue: 0.05
      - parameterName: longitudeOffsetUncertainty
        lengthUnit: metre
        unitSiRatio: 1.0
        uncertaintyMeasure: 2CEP
        defaultValue: 0.05
```

Then in the group header the parameters element simply be a list of parameter names, ie:

yaml
```
   groupName: some_group
   groupParameters: latitudeOffset, longitudeOffset, latitudeOffsetUncertainty, longitudeOffsetUncertainty
```

This would avoid duplication and remove the possibility of using inconsistent definitions in a single GGXF file.
