### ISSUE TITLE
Non-gridded parameter values

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#44]
The deformation model specification provides for specifying horizontal and vertical uncertainty values for a GGXF group either as a constant value for the group, or as a grid parameter with a value at each node of each grid in the group.  Currently GGXF does not provide for the former, other than using a custom attribute.  This was proposed in #30 but was conflated with other issues and was overlooked.

I propose that a GGXF file should provide a generic mechanism for specifying constant values for parameters that apply within a GGXF group.  The implementation would look something like below (showing just the relevant attributes of the file and group and parameters):

```yaml
parameters:
- parameterName: displacementEast
  parameterSet: displacement
  unit: metre
  unitSiRatio: 1.0
  sourceCrsAxis: 1
- parameterName: displacementNorth
  unit: metre
  unitSiRatio: 1.0
  sourceCrsAxis: 0
- parameterName: displacementHorizontalUncertainty
  unit: metre
  unitSiRatio: 1.0
  uncertaintyMeasure: 2CEP

ggxfGroups:
  - ggxfGroupName: group1
    interpolationMethod: bilinear
    groupParameters:
      - displacementEast
      - displacementNorth
    groupConstantValues:
      - parameterName: displacementHorizontalUncertainty
        parameterValue: 0.001

```
This specifies that in group1 each grid will have two parameter values at each node (displacementEast, displacementNorth).  The displacementHorizontalUncertainty is not explicitly defined at grid nodes, but a GGXF application will treat it as if it is defined at every grid node with a value of 0.001.

This mechanism allows a parameter to be treated in a consistent way in groups where it is a grid parameter and groups where it is constant, and specifies that other attributes of the parameter apply to it (eg uncertaintyMeasure).

**Comment by kevinmkelly** [comment]
This looks like a reasonable approach to me.

**Comment by RogerLott** [comment]
This is an unusual example in that we have a constant value declared for a parameter that does not appear in the ggxfGroup declaration. Just want to check that we are not building a general syntax around a specific, unusual, example.

For a file with one parameter displacementUp with this having a constant uncertainty value, the suggested syntax would map to:

parameters:
- parameterName: displacementUp
  unit: metre
  unitSiRatio: 1.0
  sourceCrsAxis: 1
- parameterName: displacementUpUncertainty
  unit: metre
  unitSiRatio: 1.0
  uncertaintyMeasure: 2SE
ggxfGroups:
  - ggxfGroupName: group2
   groupParameters:
      - displacementUp
   groupConstantValues:
      - parameterName: displacementUpUncertainty
        parameterValue: 0.001

In this example it would be easier to allow constantValue as an attribute of the parameter itself, e.g. :

parameters:
- parameterName: verticalOffset
  unit: metre
  unitSiRatio: 1.0
  sourceCrsAxis: 0
- parameterName: verticalOffsetUncertainty
  unit: metre
  unitSiRatio: 1.0
  sourceCrsAxis: 0
  constantValue: 0.001
  uncertaintyMeasure: 2SE

Then no groupParameters or groupConstantValues declaration is required. 

But having a parameter with a constant value declared as being a global parameter attribute could be confused with or misused as a default value. 

Is there requirement to allow _any_ parameter to be assigned a constant value (so made at the file header level) and then to be able to override this at the group level?

A constant value does not make sense for many parameters, but it does for parameters that are uncertainties in a deformation model. If it is only uncertainties that might have a constant value, would it be appropriate to include 'uncertainty' in the attribute name and definition (e.g. uncertaintyConstantValue)?

**Comment by ccrook** [comment]
> Is there requirement to allow any parameter to be assigned a constant value (so made at the file header level) and then to be able to override this at the group level?

There is a requirement (from the deformation model) to be able to define it at the group level.  Possibly it is not at the header level (ie for deformationModel we could do without defaultValue in parameter definitions, but we do need the group level constant specifications)

> A constant value does not make sense for many parameters, 

No it doesn't make sense for most.   However it seems to me simpler to define a general mechanism than on that applies for uncertainties.

> This is an unusual example in that we have a constant value declared for a parameter that does not appear in the ggxfGroup declaration. Just want to check that we are not building a general syntax around a specific, unusual, example.

What I am thinking is that the groupParameters defines what is defined in the grids.  Possibly gridParameters would be a better name - I was trying to avoid too many changes!  I would prefer to be more explicit, say

``` yaml
ggxfGroups:
  - ggxfGroupName: group1
    interpolationMethod: bilinear
    gridParameters:
      - displacementEast
      - displacementNorth
    constantParameters:
      - parameterName: displacementHorizontalUncertainty
        parameterValue: 0.001
```
